name: Deploy infrastructure and release Node.js and React applications

on:
  push:
    branches:
      - main

jobs:
  infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy or update infrastructure
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: neram-try
          template: ./devops/dev/main.dev.bicep
          parameters: ./devops/dev/main.dev.bicepparam
          failOnStdErr: false

  build-backend:
    needs: infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build backend
        run: |
          cd backend/src # Update the path if needed
          npm install
          npm run build --if-present

      - name: Create backend deployment package
        run: |
          cd backend
          zip -r ../backend.zip ./*

      - name: Upload backend artifact
        uses: actions/upload-artifact@v3
        with:
          name: backend
          path: backend.zip

  build-frontend:
    needs: infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies and build frontend
        run: |
          cd frontend # Update the path if needed
          npm install
          npm run build

      - name: Create frontend deployment package
        run: |
          cd frontend
          zip -r ../frontend.zip ./build # Replace `./build` if your output directory differs

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: frontend.zip

  deploy:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest
    environment:
      name: Dev

    steps:
      - name: Download backend artifact
        uses: actions/download-artifact@v3
        with:
          name: backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: carvumgroup-backend
          package: ./backend.zip
          slot-name: production

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: carvumgroup-frontend
          package: ./frontend.zip
          slot-name: production
